# Generated by Django 3.0.4 on 2022-10-23 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Okuwcy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('okuwcy_image', models.ImageField(upload_to='okuwcylar/', verbose_name='Suraty')),
                ('okuwcy_ady', models.CharField(max_length=200, verbose_name='Okuwcynyn ady')),
                ('okuwcy_familya', models.CharField(max_length=200, verbose_name='Okuwcynyn familyasy')),
                ('okuwcy_welayat', models.CharField(max_length=200, verbose_name='Welayaty')),
                ('okuwcy_etrap', models.CharField(max_length=200, verbose_name='Etraby')),
                ('okuwcy_mekdep', models.PositiveIntegerField(default=1, verbose_name='Mekdebi')),
                ('okuwcy_synp', models.PositiveIntegerField(default=4, verbose_name='Synpy')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'okuwcy',
                'verbose_name_plural': 'Okuwçylar',
            },
        ),
    ]
