# Generated by Django 3.0.4 on 2022-10-23 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ulanyjylar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='okuwcy',
            name='okuwcy_image',
        ),
    ]
