# Generated by Django 3.0.4 on 2022-10-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulanyjylar', '0002_remove_okuwcy_okuwcy_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='okuwcy',
            name='okuwcy_phone',
            field=models.PositiveIntegerField(default=62359621, max_length=8, verbose_name='Okuwcynyn telefon belgisi'),
            preserve_default=False,
        ),
    ]
