# Generated by Django 3.0.4 on 2022-10-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyzykly', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habar_image', models.ImageField(blank=True, upload_to='habarlar/', verbose_name='Habaryn suraty')),
                ('habar_name', models.CharField(max_length=250, verbose_name='Habaryn ady')),
                ('habar_text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='gosulan wagty')),
            ],
            options={
                'verbose_name': 'habar',
                'verbose_name_plural': 'Habarlar',
            },
        ),
        migrations.AlterField(
            model_name='gyzyklyvideo',
            name='gyzykly_video',
            field=models.FileField(upload_to='gyzykly_video/', verbose_name='Video'),
        ),
    ]
