# Generated by Django 3.0.4 on 2022-10-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyzykly', '0002_auto_20221022_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habar',
            name='habar_image',
            field=models.ImageField(upload_to='habarlar/', verbose_name='Habaryn suraty'),
        ),
    ]
