# Generated by Django 3.0.4 on 2022-10-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyzykly', '0003_auto_20221022_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habar',
            name='habar_image',
            field=models.ImageField(null=True, upload_to='habarlar/', verbose_name='Habaryn suraty'),
        ),
    ]
