# Generated by Django 3.0.4 on 2022-10-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyzykly', '0004_auto_20221022_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habar',
            name='habar_image',
            field=models.ImageField(default=11, upload_to='habarlar/', verbose_name='Habaryn suraty'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='habar',
            name='habar_text',
            field=models.TextField(null=True),
        ),
    ]
