# Generated by Django 3.0.4 on 2022-10-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyzykly', '0005_auto_20221022_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habar',
            name='habar_text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
