# Generated by Django 3.0.4 on 2022-10-23 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ulanyjylar', '0002_remove_okuwcy_okuwcy_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sorag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorag', models.TextField(verbose_name='Sorag')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='gosulan wagty')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ulanyjylar.Okuwcy')),
            ],
            options={
                'verbose_name': 'sorag',
                'verbose_name_plural': 'SoragJogaplar',
            },
        ),
    ]
