# Generated by Django 3.0.4 on 2022-10-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_adminehabar'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminehabar',
            name='file',
            field=models.FileField(default=11, upload_to='adminefile/'),
            preserve_default=False,
        ),
    ]
