# Generated by Django 3.0.4 on 2022-10-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_videos', '0002_auto_20221017_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ders',
            name='ders_synp',
            field=models.PositiveIntegerField(default=4, verbose_name='Dersin synpy'),
        ),
    ]
