# Generated by Django 3.0.4 on 2022-10-17 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books_videos', '0003_auto_20221017_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='books/', verbose_name='Kitap')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='gosulan wagty')),
                ('ders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books_videos.Ders')),
            ],
            options={
                'verbose_name': 'kitap',
                'verbose_name_plural': 'Kitaplar',
            },
        ),
    ]
