# Generated by Django 3.0.4 on 2022-10-17 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books_videos', '0004_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='videos/', verbose_name='Video')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='gosulan wagty')),
                ('ders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books_videos.Ders')),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'videolar',
            },
        ),
    ]
