# Generated by Django 3.0.4 on 2022-10-21 13:26

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books_videos', '0005_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bellik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema_name', models.CharField(max_length=200, verbose_name='Temanyn ady')),
                ('tema_text', ckeditor_uploader.fields.RichTextUploadingField()),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='gosulan wagty')),
                ('ders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books_videos.Ders')),
            ],
            options={
                'verbose_name': 'tema',
                'verbose_name_plural': 'Temalar',
            },
        ),
    ]
