# Generated by Django 3.0.4 on 2022-10-22 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_videos', '0008_auto_20221022_1858'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GyzyklyVideo',
        ),
        migrations.DeleteModel(
            name='Surat',
        ),
    ]
