# Generated by Django 3.0.4 on 2022-10-23 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_videos', '0010_bellik_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bellik',
            name='owner',
        ),
    ]
